server:
  port: 8080
app:
  kafka:
    topic: heatingCommands
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      group-id: monolithKafkaAclProducerGroup
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: EnableCommand:ru.smarthome.monolith.acl.command.EnableCommand,SetTemperatureCommand:ru.smarthome.monolith.acl.command.SetTemperatureCommand