openapi: 3.0.3
info:
  title: Smart Home - OpenAPI 3.0
  description: |-
    Описание REST интерфейса системы Smart Home.
  version: 1.0.0
servers:
  - url: "https://localhost:8080/api/v1"
tags:
  - name: device
    description: Управление устройствами пользователя
  - name: house
    description: Управление домами пользователя
  - name: telemetry
    description: Телеметрия
  - name: heating
    description: Отопление
paths:
  /device:
    post:
      tags:
        - device
      summary: Регистрация нового устройства пользователя
      description: Регистрация нового устройства пользователя
      operationId: addDevice
      requestBody:
        description: Регистрация нового устройства пользователя
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
        required: true
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство не найдено
      security:
        - bearerAuth: []
  /device/{deviceId}:
    get:
      tags:
        - device
      summary: Получение информации об устройстве пользователя
      description: Возвращает информацию об устройстве пользователя
      operationId: getDeviceById
      parameters:
        - name: deviceId
          in: path
          description: ID устройства
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
            application/xml:
              schema:
                $ref: "#/components/schemas/Device"
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство с указанным ID не найдено
      security:
        - bearerAuth: []
    put:
      tags:
        - device
      summary: Обновление информации об управляющем устройстве пользователя
      description: Обновление информации об управляющем устройстве пользователя по ID
      operationId: updateDevice
      parameters:
        - name: deviceId
          in: path
          description: ID устройства
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Обновление информации об управляющем устройстве пользователя
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
        required: true
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство не найдено
      security:
        - bearerAuth: []
    delete:
      tags:
        - device
      summary: Удаляет устройство пользователя
      description: Удаляет устройство пользователя
      operationId: deleteDevice
      parameters:
        - name: deviceId
          in: path
          description: ID устройства
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство не найдено
      security:
        - bearerAuth: []
  /device/findByUser:
    get:
      tags:
        - device
      summary: Поиск устройств пользователя
      description: Выполняет поиск устройств пользователя по его ID
      operationId: findDevicesByUser
      parameters:
        - name: user_id
          in: query
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Device"
        "400":
          description: Некорректный запрос
        "404":
          description: Пользователь не найден
      security:
        - bearerAuth: []
  /device/findByHouse:
    get:
      tags:
        - device
      summary: Поиск устройств относящихся к конкретному дому
      description: Выполняет поиск устройств пользователя по ID дома пользователя
      operationId: findDevicesByHouse
      parameters:
        - name: house_id
          in: query
          description: ID дома
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Device"
        "400":
          description: Некорректный запрос
        "404":
          description: Дом не найден
      security:
        - bearerAuth: []
  /house:
    post:
      tags:
        - house
      summary: Регистрация нового дома пользователя
      description: Регистрация нового дома пользователя
      operationId: addHouse
      requestBody:
        description: Регистрация нового дома пользователя
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/House"
        required: true
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/House"
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство не найдено
      security:
        - bearerAuth: []
  /house/{houseId}:
    get:
      tags:
        - house
      summary: Получение информации о доме пользователя
      description: Возвращает информацию о доме пользователя
      operationId: getHouseById
      parameters:
        - name: houseId
          in: path
          description: ID дома
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/House"
            application/xml:
              schema:
                $ref: "#/components/schemas/House"
        "400":
          description: Некорректный запрос
        "404":
          description: Дом с указанным ID не найден
      security:
        - bearerAuth: []
    put:
      tags:
        - house
      summary: Обновление информации о доме пользователя
      description: Обновление информации о доме пользователя по ID
      operationId: updateHouse
      parameters:
        - name: houseId
          in: path
          description: ID дома
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Обновление информации о доме пользователя
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/House"
        required: true
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/House"
        "400":
          description: Некорректный запрос
        "404":
          description: Дом не найден
      security:
        - bearerAuth: []
    delete:
      tags:
        - house
      summary: Удаляет дом пользователя
      description: Удаляет дом пользователя
      operationId: deleteHouse
      parameters:
        - name: houseId
          in: path
          description: ID дома
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "400":
          description: Некорректный запрос
        "404":
          description: Дом не найден
      security:
        - bearerAuth: []
  /house/findByUser:
    get:
      tags:
        - house
      summary: Поиск домов пользователя
      description: Выполняет поиск домов пользователя по его ID
      operationId: findHousesByUser
      parameters:
        - name: user_id
          in: query
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/House"
        "400":
          description: Некорректный запрос
        "404":
          description: Пользователь не найден
      security:
        - bearerAuth: []
  /telemetry/findByDevice:
    get:
      tags:
        - telemetry
      summary: Поиск телеметрии устройства за требуемый период
      description: Выполняет поиск телеметрии по ID устройства за требуемый период
      operationId: findTelemetryByDevice
      parameters:
        - name: device_id
          in: query
          description: ID устройства
          required: true
          schema:
            type: integer
            format: int64
        - name: from
          in: query
          description: Начало периода выборки телеметрии
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: Окончание периода выборки телеметрии
          required: true
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: Успешное выполнение
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Telemetry"
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство не найдено
      security:
        - bearerAuth: []
  /heating/{deviceId}/enable:
    post:
      tags:
        - heating
      summary: Включение или отключение отопления
      description: Выполняет, в зависимости от параметра, включение или отключение отопления
      operationId: enableHeating
      parameters:
        - name: deviceId
          in: path
          description: ID устройства
          required: true
          schema:
            type: integer
            format: int64
        - name: enabled
          in: query
          description: Признак включения или отключения отопления
          required: true
          schema:
            type: boolean
      responses:
        "200":
          description: Успешное выполнение
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство не найдено
      security:
        - bearerAuth: []
  /heating/{deviceId}/temperature:
    post:
      tags:
        - heating
      summary: Установка температуры отопления
      description: Выполняет установку температуры для модуля управления отоплением
      operationId: setHeatingTemperature
      parameters:
        - name: deviceId
          in: path
          description: ID устройства
          required: true
          schema:
            type: integer
            format: int64
        - name: temperature
          in: query
          description: Температура отопления
          required: true
          schema:
            type: boolean
        - name: scale
          in: query
          description: Температурная шкала. По умолчанию используется шкала Цельсия.
          required: false
          schema:
            type: string
            enum:
              - C
              - F
      responses:
        "200":
          description: Успешное выполнение
        "400":
          description: Некорректный запрос
        "404":
          description: Устройство не найдено
      security:
        - bearerAuth: []
components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        houseId:
          type: integer
          format: int64
          example: 198772
        model:
          type: string
          example: Heating control module
        manufacturer:
          type: string
          example: Honeywell
        serialNumber:
          type: string
          example: "1930tc29-1"
        enabled:
          type: boolean
          example: true
        params:
          type: string
          description: Установленные параметры устройства
          example: "temperature=20.5C"
    House:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        description:
          type: string
          example: Жилой дом
    Telemetry:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        params:
          type: string
          example: "temperature=20.5C"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
